spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/study_sync}
spring.datasource.username=${DATABASE_USERNAME:study_sync}
spring.datasource.password=${DATABASE_PASSWORD:study_sync}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.locations=classpath:db/migration/postgresql
