spring.application.name=study-sync

clockify.base-url=https://api.clockify.me/api/v1
clockify.api-key=OWViZDdjODItMWVmOS00MjIzLWE0M2UtYjMwYmE5NGRjMTYy
clockify.user-id=696eda7e173e8150a15a6ee7
clockify.workspace-id=696eda7d173e8150a15a6ee2