spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.application.name=study-sync

clockify.base-url=https://api.clockify.me/api/v1
clockify.api-key=${CLOCKIFY_API_KEY}
clockify.user-id=696eda7e173e8150a15a6ee7
clockify.workspace-id=696eda7d173e8150a15a6ee2