CREATE TABLE weekly_study (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    total_minutes BIGINT NOT NULL,
    notion_time VARCHAR(32) NOT NULL,
    synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_weekly_study_week_start UNIQUE (week_start)
);

CREATE TABLE sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    triggered_by VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    total_minutes BIGINT,
    error_message VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_sync_runs_week_start ON sync_runs (week_start);
