CREATE TABLE subject_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(256) NOT NULL,
    weekly_minutes INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_subject_goals_subject UNIQUE (subject),
    CONSTRAINT chk_subject_goals_weekly_minutes CHECK (weekly_minutes BETWEEN 1 AND 10080)
);

CREATE INDEX idx_subject_goals_subject ON subject_goals (subject);
